apiVersion: v1
data:
  artifactRepository: |
    archiveLogs: true
    h3:
      bucket: my-bucket
      storageUri: redis://127.0.0.1:6379
  metricsConfig: |
    disableLegacy: true
    enabled: true
    path: /metrics
    port: 9090
  links: |
    - name: Example Workflow Link
      scope: workflow
      url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}
    - name: Example Pod Link
      scope: pod
      url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
